### ISSUE TITLE
avg_age_per_indu underlying code requires mongodb v4 + due to $dateFromString query 

### ISSUE THREAD

**Issue by MilkyTA** [MilkyTA/test_colibri#13]
$dateFromString 
Field format is not implemented until mongo v4. Updating my local mongo server from v3.6 is proving to be complex. 

Reinstall mongodb to v4 and test and improve avg_age_per_indu  function

**Comment by MilkyTAsefa** [comment]
Tested with mongodb v4.4 and proven to work as written
